image: python:3.11

stages:
  - lint
  - type
  - test

before_script:
  - pip install -e '.[dev]'

lint:
  stage: lint
  script:
    - ruff check .

type:
  stage: type
  script:
    - mypy src

test:
  stage: test
  script:
    - pytest -q
